Description: >
  Stack deploys the servers and other resources for Udagram web application

######################################### Parameters ############################################################
Parameters:
  EnvironmentName:
    Description: Name prefixed to all the provisioned resources.
    Type: String
  ServerAMIId:
    Description: AMI ID for the provisioned EC2 instances.
    Type: String
  InstanceType:
    Description: EC2 instance type
    Type: String

######################################## Resources ###############################################################
Resources:
  ##### Load Balancer Security Group #####
  LBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to our load balancer
      VpcId:
        Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress: #Allow inbound traffic on port 80
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress: #Allow outbound traffic on port 80
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ##### Udagram App Servers Security Group #####
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to our hosts and SSH from local only
      VpcId:
        Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress: #Allow inbound traffic on port 80 for accessing application and on port 22 for SSH in case of troubleshooting any issues.
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress: # Allow outbound traffic on all ports to enable the download of updates or patches.
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0

  ##### Launch configuration that will be used when server will spin up #####
  WebAppLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt-get update -y
          apt-get install unzip -y
          apt-get install apache2 -y
          cd /var/www/html
          wget https://raw.githubusercontent.com/KennedyUC/cloudDevOps-udacity/main/cloudFormation/udagram-web.zip
          unzip -o udagram-web.zip
          rm udagram-web.zip
          systemctl enable apache2.service
          systemctl start apache2.service
      ImageId: !Ref ServerAMIId
      SecurityGroups:
        - Ref: WebServerSecurityGroup
      InstanceType: !Ref InstanceType
      BlockDeviceMappings:
        - DeviceName: "/dev/sdk"
          Ebs:
            VolumeSize: "10"

  ##### Udagram App Auto Scaling Group #####
  WebAppGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - Fn::ImportValue: !Sub "${EnvironmentName}-PRIVATE-NETS"
      LaunchConfigurationName:
        Ref: WebAppLaunchConfig
      MinSize: "2"
      MaxSize: "4"
      TargetGroupARNs:
        - Ref: WebAppTargetGroup

  ##### Load balancer for public subnets with load balancer security group attached #####
  WebAppLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
        - Fn::ImportValue: !Sub "${EnvironmentName}-PUBLIC-SN01"
        - Fn::ImportValue: !Sub "${EnvironmentName}-PUBLIC-SN02"
      SecurityGroups:
        - Ref: LBSecurityGroup

  ##### Load Balancer Listener #####
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn:
            Ref: WebAppTargetGroup
      LoadBalancerArn:
        Ref: WebAppLB
      Port: "80"
      Protocol: HTTP

  ##### Load Balancer Listner Rule #####
  ALBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
        - Type: forward
          TargetGroupArn: !Ref "WebAppTargetGroup"
      Conditions:
        - Field: path-pattern
          Values: [/]
      ListenerArn: !Ref "Listener"
      Priority: 1

  ##### Target Group #####
  WebAppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 8
      HealthyThresholdCount: 2
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 5
      VpcId:
        Fn::ImportValue:
          Fn::Sub: "${EnvironmentName}-VPCID"

  ################################################## Outputs ###################################################
Outputs:
  WebAppLBDNSName:
    Description: The website URL DNS name or Public URL of the Load Balancer.
    Value: !Join ["", ["http://", !GetAtt WebAppLB.DNSName]]
    Export:
      Name: !Sub ${EnvironmentName}-LB-DNSName